pipeline {
    agent any

    tools {
        maven 'Maven'   // we’ll configure this in Jenkins
    }

    stages {

        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/nikimanvi/devsecops-project.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
